import Images from "../../../../assets/images";

export const Washes = [
  {
    id: "1",
    category: "Membership",
    category1:"Monthly",
    title: "Test- Update Schedule1",
    features: ["air dry", "fusion wax"],
    rate: "Price",
    price: "$99.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "2",
    category: "Membership",
    category1:"Monthly",
    title: "Schedule Pawan",
    features: [
      "3 step ceramics",
      "air dry",
      "carnauba hot wax",
      "clear coat sealant",
      "fusion bath",
      "high-pressure body",
    ],
    rate: "Price",
    price: "$79.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "3",
    category: "Membership",
    category1:"Monthly",
    title: "Deepali Test Schedule",
    features: ["3 step ceramics", "bug prep"],
    rate: "Price",
    price: "$50.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "4",
    category: "Membership",
    category1:"Monthly",
    title: "Deepali Test Schedule",
    features: ["3 step ceramics", "bug prep"],
    rate: "Price",
    price: "$50.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "5",
    category: "Membership",
    category1:"Yearly",
    title: "Deepali Schedule",
    features: ["bug buster", "air dry"],
    rate: "Price",
    Discount:"12%",
    price: "$500.00",
    image: Images.MembershipImage,
  },
  {
    id: "6",
    category: "Membership",
    category1:"Yearly",
    title: "Appinventiv Wash Update",
    features: [
      "bug buster",
      "bug blast",
      "carnauba hot wax",
      "rain repel",
      "tire shine",
      "wash",
      "wheel blaster",
    ],
    rate: "Price",
    Discount:"15%",
    price: "$12.00",
    image:Images.MembershipImage,
  },
  {
    id: "7",
    category: "Membership",
    category1:"Monthly",
    title: "ajay test Gaurav Garg!!",
    features: [
      "1 step ceramics",
      "2 step ceramics",
      "3 step ceramics",
      "air dry",
      "bug blast",
      "carnauba hot wax",
    ],
    rate: "Price",
    Discount:"15%",
    price: "$120.00",
    image:Images.MembershipImage,
  },
  {
    id: "8",
    category: "Membership",
    category1:"Yearly",
    title: "Abandoned Plane",
    features: ["1 step ceramics", "ceramic rain repel"],
    rate: "Price",
    Discount:"15%",
    price: "$299.00",
    image: Images.MembershipImage,
  },
];


export const Washbook = [
  {
    id: "1",
    category: "Courses",
    category1: "Technology",
    title: "Introduction to Artificial Intelligence",
    features: ["AI Basics", "Applications"],
    rate: "Price",
    price: "$499.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "2",
    category: "Courses",
    category1: "Web Development",
    title: "Web Development with React",
    features: ["React.js", "Modern UI"],
    rate: "Price",
    price: "$799.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "3",
    category: "Courses",
    category1: "Data Science",
    title: "Data Science Fundamentals",
    features: ["Data Analysis", "Visualization"],
    rate: "Price",
    price: "$699.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "4",
    category: "Courses",
    category1: "Machine Learning",
    title: "Machine Learning Algorithms",
    features: ["Regression", "Classification", "Clustering"],
    rate: "Price",
    price: "$999.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "5",
    category: "Courses",
    category1: "Blockchain",
    title: "Introduction to Blockchain",
    features: ["Decentralization", "Smart Contracts"],
    rate: "Price",
    price: "$549.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "6",
    category: "Courses",
    category1: "Mobile Development",
    title: "iOS App Development",
    features: ["Swift", "UI Kit"],
    rate: "Price",
    price: "$899.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "7",
    category: "Courses",
    category1: "Data Analysis",
    title: "Python for Data Analysis",
    features: ["Pandas", "NumPy"],
    rate: "Price",
    price: "$749.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "8",
    category: "Courses",
    category1: "Security",
    title: "Cybersecurity Best Practices",
    features: ["Network Security", "Encryption"],
    rate: "Price",
    price: "$599.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "9",
    category: "Courses",
    category1: "Cloud",
    title: "Cloud Computing Essentials",
    features: ["AWS Basics", "Scalability"],
    rate: "Price",
    price: "$799.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "10",
    category: "Courses",
    category1: "Design",
    title: "Introduction to UX Design",
    features: ["UI Principles", "Wireframing"],
    rate: "Price",
    price: "$649.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
];


export const giftCards = [
  {
    id: "1",
    category: "Gift Card",
    category1: "E-Gift",
    title: "Amazon E-Gift Card",
    features: ["Instant Delivery", "No Expiry"],
    rate: "Price",
    price: "$50.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "2",
    category: "Gift Card",
    category1: "Physical",
    title: "Flipkart Shopping Card",
    features: ["Valid for 1 Year", "Multiple Uses"],
    rate: "Price",
    price: "$100.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "3",
    category: "Gift Card",
    category1: "E-Gift",
    title: "Myntra Fashion Card",
    features: ["Fashion & Lifestyle", "Instant Email Delivery"],
    rate: "Price",
    price: "$75.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "4",
    category: "Gift Card",
    category1: "E-Gift",
    title: "Spotify Premium Gift",
    features: ["3-Month Subscription", "Music & Podcasts"],
    rate: "Price",
    price: "$30.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "5",
    category: "Gift Card",
    category1: "Physical",
    title: "Starbucks Coffee Card",
    features: ["Nationwide Redeem", "Reloadable"],
    rate: "Price",
    price: "$60.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "6",
    category: "Gift Card",
    category1: "E-Gift",
    title: "Google Play Store Card",
    features: ["Apps & Games", "Instant Email Delivery"],
    rate: "Price",
    price: "$40.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "7",
    category: "Gift Card",
    category1: "E-Gift",
    title: "Apple App Store Card",
    features: ["iOS Apps", "Music & Movies"],
    rate: "Price",
    price: "$100.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "8",
    category: "Gift Card",
    category1: "Physical",
    title: "Nike Sports Gift Card",
    features: ["Sportswear", "Shoes", "Accessories"],
    rate: "Price",
    price: "$150.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "9",
    category: "Gift Card",
    category1: "E-Gift",
    title: "Zomato Food Card",
    features: ["Food Delivery", "No Expiry"],
    rate: "Price",
    price: "$25.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "10",
    category: "Gift Card",
    category1: "E-Gift",
    title: "Netflix Gift Card",
    features: ["1-Month Subscription", "HD Streaming"],
    rate: "Price",
    price: "$15.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
];


export const memberships = [
  {
    id: "1",
    category: "Membership",
    category1: "Monthly",
    title: "Basic Wash Plan",
    features: ["Exterior Wash", "Air Dry"],
    rate: "Price",
    price: "$29.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "2",
    category: "Membership",
    category1: "Monthly",
    title: "Premium Wash Plan",
    features: ["3 Step Ceramics", "Carnauba Hot Wax", "Tire Shine"],
    rate: "Price",
    price: "$59.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "3",
    category: "Membership",
    category1: "Monthly",
    title: "Ultra Shine Plan",
    features: ["Ceramic Coating", "Rain Repel", "Bug Prep"],
    rate: "Price",
    price: "$79.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
  {
    id: "4",
    category: "Membership",
    category1: "Yearly",
    title: "Family Wash Plan",
    features: ["Unlimited Washes", "4 Vehicles", "Fusion Wax"],
    rate: "Price",
    price: "$499.00",
    Discount: "10%",
    image: Images.MembershipImage,
  },
  {
    id: "5",
    category: "Membership",
    category1: "Yearly",
    title: "Corporate Plan",
    features: ["10 Vehicles", "Monthly Detailing", "Clear Coat Sealant"],
    rate: "Price",
    price: "$999.00",
    Discount: "15%",
    image:Images.MembershipImage,
  },
  {
    id: "6",
    category: "Membership",
    category1: "Monthly",
    title: "Weekend Special Plan",
    features: ["Valid on Sat & Sun", "Bug Buster", "Wheel Blaster"],
    rate: "Price",
    price: "$39.00",
    Discount: "0%",
    image: Images.MembershipImage,
  },
  {
    id: "7",
    category: "Membership",
    category1: "Yearly",
    title: "Luxury Car Plan",
    features: ["Ceramic Rain Repel", "Deep Interior Cleaning", "Fusion Bath"],
    rate: "Price",
    price: "$799.00",
    Discount: "20%",
    image: Images.MembershipImage,
  },
  {
    id: "8",
    category: "Membership",
    category1: "Monthly",
    title: "Student Wash Plan",
    features: ["Discounted Price", "Basic Wash", "Air Dry"],
    rate: "Price",
    price: "$19.00",
    Discount: "5%",
    image: Images.MembershipImage,
  },
  {
    id: "9",
    category: "Membership",
    category1: "Yearly",
    title: "Platinum Detailing Plan",
    features: [
      "Full Detailing",
      "Ceramic Coating",
      "Leather Conditioning",
      "Wax & Sealant",
    ],
    rate: "Price",
    price: "$1,499.00",
    Discount: "25%",
    image: Images.MembershipImage,
  },
  {
    id: "10",
    category: "Membership",
    category1: "Monthly",
    title: "Eco Wash Plan",
    features: ["Waterless Wash", "Biodegradable Products"],
    rate: "Price",
    price: "$35.00",
    Discount: "0%",
    image:Images.MembershipImage,
  },
];
