import image1 from "./assets/Membership.png";

const DATA = [
  {
    id: "1",
    category: "Membership",
    category1:"Monthly",
    title: "Test- Update Schedule1",
    features: ["air dry", "fusion wax"],
    rate: "Price",
    price: "$99.00",
    image: image1,
  },
  {
    id: "2",
    category: "Membership",
    category1:"Monthly",
    title: "Schedule Pawan",
    features: [
      "3 step ceramics",
      "air dry",
      "carnauba hot wax",
      "clear coat sealant",
      "fusion bath",
      "high-pressure body",
    ],
    rate: "Price",
    price: "$79.00",
    image: image1,
  },
  {
    id: "3",
   category: "Membership",
    category1:"Monthly",
    title: "Deepali Test Schedule",
    features: ["3 step ceramics", "bug prep"],
    rate: "Price",
    price: "$50.00",
    image: image1,
  },
  {
    id: "4",
   category: "Membership",
    category1:"Monthly",
    title: "Deepali Test Schedule",
    features: ["3 step ceramics", "bug prep"],
    rate: "Price",
    price: "$50.00",
    image: image1,
  },
  {
    id: "5",
  category: "Membership",
    category1:"Yearly",
    title: "Deepali Schedule",
    features: ["bug buster", "air dry"],
    rate: "Price",
    price: "$500.00",
    image: image1,
  },
  {
    id: "6",
   category: "Membership",
    category1:"Yearly",
    title: "Appinventiv Wash Update",
    features: [
      "bug buster",
      "bug blast",
      "carnauba hot wax",
      "rain repel",
      "tire shine",
      "underbody wash",
      "wash",
      "underbody rinse",
      "wheel blaster",
    ],
    rate: "Price",
    price: "$12.00",
    image: image1,
  },
  {
    id: "7",
   category: "Membership",
    category1:"Monthly",
    title: "ajay test Gaurav Garg!!",
    features: [
      "1 step ceramics",
      "2 step ceramics",
      "3 step ceramics",
      "air dry",
      "bug blast",
      "carnauba hot wax",
    ],
    rate: "Price",
    price: "$120.00",
    image: image1,
  },
  {
    id: "8",
  category: "Membership",
    category1:"Yearly",
    title: "Abandoned Plane",
    features: ["1 step ceramics", "ceramic rain repel"],
    rate: "Price",
    price: "$299.00",
    image: image1,
  },
];

export default DATA;
